# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pcr_amplify <- function(temp, cycle, efficiency_amplification, ratio_mutation) {
    .Call('_CellBarcodeSim_pcr_amplify', PACKAGE = 'CellBarcodeSim', temp, cycle, efficiency_amplification, ratio_mutation)
}

